/**
 * Summarise the reading material kept outside the submission.
 *
 * `research/` is excluded from version control. Its contents are still worth
 * describing in machine-readable form, so that the survey behind the design
 * decisions is auditable without shipping any of it.
 *
 * The output is written into `research/`, never into the shipped tree.
 *
 * Usage:
 *
 *     npm run research:matrix
 */

import { readdirSync, readFileSync, existsSync, writeFileSync, statSync } from "node:fs";
import { execFileSync } from "node:child_process";
import path from "node:path";

import { REPO_ROOT, log } from "./_shared.mjs";

const SAMPLES_DIR = path.join(REPO_ROOT, "research", "samples");

function gitOrigin(directory) {
  try {
    return execFileSync("git", ["-C", directory, "remote", "get-url", "origin"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return "";
  }
}

function gitHead(directory) {
  try {
    return execFileSync("git", ["-C", directory, "rev-parse", "--short", "HEAD"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return "";
  }
}

function countFiles(directory, depth = 0) {
  if (depth > 3) return 0;
  let total = 0;
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    if (entry.name === ".git" || entry.name === "node_modules") continue;
    const absolute = path.join(directory, entry.name);
    if (entry.isDirectory()) total += countFiles(absolute, depth + 1);
    else if (statSync(absolute).isFile()) total += 1;
  }
  return total;
}

function firstReadme(directory) {
  for (const name of readdirSync(directory)) {
    if (/^readme(\.md|\.rst|\.txt)?$/i.test(name)) {
      const text = readFileSync(path.join(directory, name), "utf8");
      const line = text
        .split(/\r?\n/)
        .map((value) => value.replace(/^#+\s*/, "").trim())
        .find((value) => value.length > 20 && !value.startsWith("!") && !value.startsWith("["));
      return line ?? "";
    }
  }
  return "";
}

if (!existsSync(SAMPLES_DIR)) {
  log.fail("research/samples does not exist; nothing to describe");
  process.exit(1);
}

const rows = [];
for (const entry of readdirSync(SAMPLES_DIR, { withFileTypes: true })) {
  if (!entry.isDirectory()) continue;
  const directory = path.join(SAMPLES_DIR, entry.name);
  rows.push({
    id: entry.name,
    origin: gitOrigin(directory),
    head: gitHead(directory),
    files: countFiles(directory),
    summary: firstReadme(directory),
  });
}

const lines = [
  "# Sample survey",
  "",
  "Generated by `npm run research:matrix`. This file lives in `research/`, which is",
  "excluded from version control. Nothing here is shipped.",
  "",
  `Sampled directories: ${rows.length}`,
  "",
  "| # | Directory | Upstream | Revision | Files | First descriptive line |",
  "| --- | --- | --- | --- | --- | --- |",
];

rows.forEach((row, index) => {
  const upstream = row.origin ? row.origin.replace(/\|/g, "\\|") : "(not a checkout)";
  const summary = row.summary.replace(/\|/g, "\\|").slice(0, 120);
  lines.push(`| ${index + 1} | \`${row.id}\` | ${upstream} | \`${row.head || "-"}\` | ${row.files} | ${summary} |`);
});

lines.push("", "## What was taken from the survey", "");
lines.push("- The distinction between a provisional judgment and a final one is the whole product.");
lines.push("- A proof campaign needs a deliberately wrong arm, not only a right one.");
lines.push("- Every claim in the submission is backed by a file a reader can open.");

writeFileSync(path.join(REPO_ROOT, "research", "SAMPLE_MATRIX.md"), lines.join("\n") + "\n", "utf8");

log.step("Sample survey");
log.ok(`described ${rows.length} sampled directories`);
log.ok("wrote research/SAMPLE_MATRIX.md");
